# Generated by Django 5.0.6 on 2024-07-02 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='otp_max_out',
        ),
    ]
