# Generated by Django 4.2.16 on 2025-09-09 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
    ]
