# Generated by Django 5.0.6 on 2024-07-11 17:36

import Users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_remove_usermodel_otp_max_out'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/', validators=[Users.models.validate_file_size]),
        ),
    ]
