# Generated by Django 5.0.6 on 2024-08-11 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_alter_usermodel_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='is_trusted',
            field=models.BooleanField(default=False),
        ),
    ]
