# Generated by Django 4.2.16 on 2025-09-14 07:36

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnail/', validators=[products.models.validate_file_size]),
        ),
    ]
