# Generated by Django 5.0.6 on 2024-07-28 21:17

import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_owner_alter_product_stone_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(upload_to='thumbnail', validators=[products.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='products', validators=[products.models.validate_file_size]),
        ),
    ]
