# Generated by Django 5.0.6 on 2024-07-31 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='wages',
            new_name='wage',
        ),
    ]
