# Generated by Django 5.0.6 on 2024-08-11 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0006_order_discount_amount_order_final_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='final_price',
        ),
    ]
